name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install 7-Zip on Windows
        if: matrix.os == 'windows-latest'
        run: choco install 7zip -y
        shell: powershell

      - name: Download and extract binary in Linux
        if: matrix.os == 'ubuntu-22.04'
        run: |
          wget --quiet -O binary-file.tar.xz https://github.com/hiroi-sora/PaddleOCR-json/releases/download/v1.4.0/PaddleOCR-json_v1.4.0_debian_gcc_x86-64.tar.xz
          mkdir -p extracted
          tar -xf binary-file.tar.xz -C extracted
          echo "PADDLEOCR_JSON_EXE_PATH=$(pwd)/extracted/PaddleOCR-json_v1.4.0_debian_gcc_x86-64/bin/PaddleOCR-json" >> $GITHUB_ENV
          echo "PADDLEOCR_JSON_TEST_IMG_PATH=$(pwd)/res/test.png" >> $GITHUB_ENV
        shell: bash

      - name: Download and extract binary in Windows
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri https://github.com/hiroi-sora/PaddleOCR-json/releases/download/v1.4.0/PaddleOCR-json_v1.4.0_windows_x86-64.7z　-OutFile "binary-file.zip"
          New-Item -ItemType Directory -Path "extracted" -Force
          7z x binary-file.7z -oextracted
          $PADDLEOCR_JSON_EXE_PATH = "$(pwd)\extracted\PaddleOCR-json_v1.4.0\PaddleOCR-json.exe"
          $PADDLEOCR_JSON_TEST_IMG_PATH = "$(pwd)\res\test.png"
          echo "PADDLEOCR_JSON_EXE_PATH=$PADDLEOCR_JSON_EXE_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PADDLEOCR_JSON_TEST_IMG_PATH=$PADDLEOCR_JSON_TEST_IMG_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Run tests
        run: mvn -B test
        env:
          PADDLEOCR_JSON_EXE_PATH: ${{ env.PADDLEOCR_JSON_EXE_PATH }}
          PADDLEOCR_JSON_TEST_IMG_PATH: ${{ env.PADDLEOCR_JSON_TEST_IMG_PATH }}
